# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'beltcalc_reactnative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for beltcalc_reactnative

  target 'beltcalc_reactnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'beltcalc_reactnativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'